COINS = [
    "BTCUSDT", "ETHUSDT", "SOLUSDT", "BNBUSDT", "XRPUSDT",
    "DOGEUSDT", "ADAUSDT", "AVAXUSDT", "DOTUSDT", "LINKUSDT",
    "POLUSDT", "LTCUSDT", "BCHUSDT", "ATOMUSDT", "UNIUSDT",
    "NEARUSDT", "APTUSDT", "FILUSDT", "ARBUSDT", "OPUSDT"
]

# HAFTA İÇİ TIMEFRAME'LERİ (Pazartesi-Cuma: 1h + 4h birlikte)
TIMEFRAME_MAIN_HAFTA_ICI = "1h"
TIMEFRAME_MTF_HAFTA_ICI = "4h"

# HAFTA SONU TIMEFRAME'İ (Cumartesi-Pazar: sadece 15m)
TIMEFRAME_MAIN_HAFTA_SONU = "15m"

# VETO (her zaman 4h - BTC yönü)
TIMEFRAME_VETO = "4h"

# SABİT POZİSYON
ISLEM_BASINA = 10
BUTCE_SANAL = 100
KALDIRAC = 10
MAX_POZISYON = 5
MAX_AYNI_YON = 3

# RİSK
GUNLUK_KAYIP_LIMITI = 0.03
MAX_DRAWDOWN = 0.20
DRAWDOWN_REDUCE = 0.15
MIN_ISLEM_TUTAR = 2

# İNDİKATÖR
MRC_LENGTH = 100
ATR_PERIOD = 14
RSI_PERIOD = 14
MIN_SKOR = 7

# AKILLI SL/TP
AKILLI_SL_TP = True
SL_MIN_ATR = 1.0
SL_MAX_ATR = 2.5
TP_MIN_ATR = 2.0
TP_MAX_ATR = 6.0

# DİĞER
KOMISYON = 0.0008
SLIPPAGE = 0.0005

# HAFTA İÇİ: 1 saatte bir tara (3600 saniye)
TARAMA_ARALIGI_HAFTA_ICI = 3600

# HAFTA SONU: 15 dakikada bir tara (900 saniye)
TARAMA_ARALIGI_HAFTA_SONU = 900

COOLDOWN_DAKIKA = 60

print("✅ Config yüklendi (Hafta içi 1h+4h / Hafta sonu 15m)")