COINS = [
    "PEPEUSDT", "ADAUSDT", "DOTUSDT", "APTUSDT", "UNIUSDT",
    "OPUSDT", "NEARUSDT", "ARBUSDT", "LTCUSDT", "DOGEUSDT"
]

# TIMEFRAME
TIMEFRAME_MAIN_HAFTA_ICI = "1h"
TIMEFRAME_MTF_HAFTA_ICI = "4h"
TIMEFRAME_MAIN_HAFTA_SONU = "15m"
TIMEFRAME_VETO = "4h"

# POZİSYON
ISLEM_BASINA = 10
BUTCE_SANAL = 100
KALDIRAC = 10
MAX_POZISYON = 5
MAX_AYNI_YON = 3

# RİSK
GUNLUK_KAYIP_LIMITI = 0.03
MAX_DRAWDOWN = 0.20
DRAWDOWN_REDUCE = 0.15
MIN_ISLEM_TUTAR = 2

# İNDİKATÖR - SADELEŞTİ
MRC_LENGTH = 100
ATR_PERIOD = 14
RSI_PERIOD = 14
MIN_SKOR = 4  # ESKİ 7 İDİ, 4 YAPTIK

# SABİT SL/TP - AKILLI SİSTEM KAPALI
AKILLI_SL_TP = False
SL_ATR = 1.0
TP_ATR = 2.0
SL_MIN_ATR = 1.0
SL_MAX_ATR = 1.0
TP_MIN_ATR = 2.0
TP_MAX_ATR = 2.0

# DİĞER
KOMISYON = 0.0008
SLIPPAGE = 0.0005
TARAMA_ARALIGI_HAFTA_ICI = 3600
TARAMA_ARALIGI_HAFTA_SONU = 900
COOLDOWN_DAKIKA = 60

print("✅ Config yüklendi (Top10 - Skor4 - RR2.0 - OR)")
